### ISSUE TITLE
Feature Request: Enabling/Disabling package from appsettings/DI 

### ISSUE THREAD

**Issue by aochmann** [jesperweber/Our.Umbraco.HeadlessPreview#2]
Hi Jesper,
I'd like to suggest a feature request for the option to enable/disable preview. This option would be useful for projects that share a common code base and are not headless - boilerplates. This could be a great option for the package registration with the option to disable/enable through settings.

I was investigating a bit how this could be done, but as I saw that we are loading the configuration from appsettings and then we use it from the dashboard into a database. We would need somehow to change the endpoints behaviour and option to control. Or we could change the behaviour and only use appsettings (or doing the registration from DI) for the package enabling/disabling and when disabled then greying out the dashboard in backoffice until it is again enabled.

Please let me know what you think.

Cheers,
Adrian

**Comment by jesperweber** [comment]
Hi @aochmann Thank you for sharing your feature request :-)

Do you want the plugin to be able to disable the preview button for the entire Umbraco installation, meaning all sites in the Umbraco installation or only for specific sites in a Umbraco installation?

Yes you can configure the package from either appsettings.json or from the UI. If you have configuration in the appsettings.json file the UI will be disabled and not saved in the database. If you have no configuration in the appsettings.json file you can use the UI and the settings will be store in the database.

![image](https://github.com/jesperweber/Our.Umbraco.HeadlessPreview/assets/2575817/00515b72-47a2-47bb-9974-c18aab5272ca)

**Comment by aochmann** [comment]
> Hi @aochmann Thank you for sharing your feature request :-)
> 
> Do you want the plugin to be able to disable the preview button for the entire Umbraco installation, meaning all sites in the Umbraco installation or only for specific sites in a Umbraco installation?
> 
> Yes you can configure the package from either appsettings.json or from the UI. If you have configuration in the appsettings.json file the UI will be disabled and not saved in the database. If you have no configuration in the appsettings.json file you can use the UI and the settings will be store in the database.
> 
> ![image](https://private-user-images.githubusercontent.com/2575817/304215669-00515b72-47a2-47bb-9974-c18aab5272ca.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAyNDgxNDksIm5iZiI6MTcxMDI0Nzg0OSwicGF0aCI6Ii8yNTc1ODE3LzMwNDIxNTY2OS0wMDUxNWI3Mi00N2EyLTQ3YmItOTk3NC1jMThhYWI1MjcyY2EucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMxMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMTJUMTI1MDQ5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NTE1ZWU5NDM2OTYyZWIwMTczNjdhNjAwYjdkNzM1MzdlMjY5MTllMjJhNWYwZDA0ZjViNmQ3OTlmZDQ4MWNlYSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.Ai2N_Dxjbb27mbePG_so4kpY9_9L4ULtjTk_TyNF7k0)

Hi @jesperweber 
sorry for the late answer.
Yes disabling the package fully from configuration. Something like that:

```json
"HeadlessPreview": {
    "Enabled": false,
    "TemplateUrl": "https://mysite.com/api/preview?slug={slug}&secret=mySecret"
}
```

and inside registration we could have options:

```csharp
umbracoBuilder.AddHeadlessPreview(); //here will check if enabled or not
```

What do you think about that?

**Comment by jesperweber** [comment]
It makes sense and it's defiantly doable, I will look into it :-)

**Comment by jesperweber** [comment]
Hi @aochmann,

A new version 2.2.0 has just been released with the option to disable the headless preview and more :-)

Take a look at it: https://github.com/jesperweber/Our.Umbraco.HeadlessPreview/releases/tag/2.2.0
